spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datask?useSSL=false
    username: datask
    password: datask
  profiles:
    active: mysql
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect