app:
  c3p0:
    datasource: 
      jdbc-url: jdbc:mysql://${OPENSHIFT_MYSQL_DB_HOST}:${OPENSHIFT_MYSQL_DB_PORT}/${OPENSHIFT_APP_NAME}?useSSL=false
      user: ${OPENSHIFT_MYSQL_DB_USERNAME}
      password: ${OPENSHIFT_MYSQL_DB_PASSWORD} 
      driver-class: com.mysql.jdbc.Driver
  properties:
    cors:
      allowed-origins: '*'
      allowed-methods: GET, PUT, POST, DELETE, OPTIONS
      allowed-headers: '*'
      exposed-headers: Link,FileName
      allow-credentials: true
      max-age: 1800
    security:
      authentication:
        jwt:
          secret: 
          tokenValidityInSeconds: 86400
spring:
  profiles:
    active: openshift
  jpa: 
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
      show-sql: false
logging:
  config: classpath:logback-pro.xml