app:
  properties:
    swagger:
      description: Version @version@ of datask
      name: Datask
spring:
  application:
    name: '@artifactId@'
    group: '@groupId@'
    version: '@project.artifact.selectedVersion.majorVersion@'
    prefix: /api/v
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: datask-hikari
      minimum-idle: 1
      maximum-pool-size: 10
management.context-path: /manage