app:
  c3p0:
    datasource: 
      jdbc-url: jdbc:mysql://localhost:3306/bm?useSSL=false
      user: bm
      password: bm 
      driver-class: com.mysql.jdbc.Driver
spring:
  profiles:
    active: mysql
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect